
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
# 将光标设置为光束并在允许时开始闪烁
# shape = "Beam"
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 13.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
offset = { x = 0, y = 0 }

[keyboard]
bindings = [
  { action = "SpawnNewInstance", key = "T", mods = "Control" },
  { action = "CreateNewWindow", key = "N", mods = "Command" },
  { action = "ToggleFullscreen", key = "F", mods = "Command|Control" },
]


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
blur = true
decorations = "buttonless"
# 背景不透明度
opacity = 0.95
# 在终端内容周围均匀分布额外的填充
dynamic_padding = true
# 在窗口周围添加的空白区域
padding = { x = 3, y = 3 }
# 窗口启动位置
position = { x = 3, y = 3 }
# 窗口尺寸
dimensions = { columns = 80, lines = 30 }

[scrolling]
# 自动滚动至最新行
history = 20000

[general]
# 自动刷新
live_config_reload = true
import = ["/Users/asins/.config/alacritty/theme/snazzy.toml"]
