import = ["/Users/asins/.config/alacritty/theme/snazzy.toml"]
# 自动刷新
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 13.0
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
offset = { x = 0, y = 0 }

[keyboard]
bindings = [
  { action = "SpawnNewInstance", key = "T", mods = "Control" },
  { action = "CreateNewWindow", key = "N", mods = "Command" },
  { action = "ToggleFullscreen", key = "F", mods = "Command|Control" },
]


[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
# decorations = "buttonless"
decorations = "Transparent"
opacity = 0.95
dynamic_padding = true
padding = { x = 3, y = 3 }
position = { x = 3, y = 3 }

[scrolling]
# 自动滚动至最新行
history = 20000
